프로젝트 회고 조회/상세api 작업
f-lab-edu/resume-project pull request #4
Opened 2024-11-22 01:45 UTC by dbeod2

프로젝트 회고 목록조회/상세 API 작업 하여 PR전달드립니다!

2024-11-22 15:48 UTC, f-lab-justin requested changes
@dbeod2 
한번 살펴보세요~

2024-11-22 15:48 UTC, f-lab-justin commented on src/main/java/com/api/resume/adapter/controller/ResumeReviewController.java
> +        return ResponseEntity.ok().body(results);
@dbeod2 
요기에 ResponseEntity.ok()가 반복되는 데 없어도 될 수 있습니다.
한번 살펴보세요!

2024-11-22 15:48 UTC, f-lab-justin commented on src/main/java/com/api/resume/adapter/controller/ResumeReviewController.java
> +        List<ResumeReviewListResponse> results = ResumeReviewResponseConverter.INSTANCE.toResumeReviewListResponses(resumeReviewList);
@dbeod2 
이 컨버터를 컨트롤러에서 꼭 써야할까요?? 
ResumeReviewListResponse안으로 숨겨보면 어떨까요?

2024-11-22 15:48 UTC, f-lab-justin commented on src/main/java/com/api/resume/adapter/persistence/ResumeReviewSpecificationBuilder.java
> +        Specification<ResumeReview> spec = Specification.where(null);
@dbeod2 
아~ 혹시 querydsl로 작성해본적 있으실까요??

2024-11-22 15:48 UTC, f-lab-justin commented on src/main/java/com/api/resume/application/service/ResumeReviewQueryService.java
> +        return ResumeReviewDtoConverter.INSTANCE.toResumeReviewListDtos(resumeReviews);
@dbeod2 
여기서도 converter보다는 ResumeReviewListDto 안으로 숨겨보면 어떨까요?

2024-11-22 15:48 UTC, f-lab-justin commented on src/main/java/com/api/resume/adapter/proxy/ResumeReviewProxy.java
> +public class ResumeReviewProxy {
@dbeod2 
요거 용어가 신기하네요..proxy를 사용하신 이유가 있을까요??

2024-11-23 08:22 UTC, dbeod2 commented on src/main/java/com/api/resume/adapter/proxy/ResumeReviewProxy.java
> +public class ResumeReviewProxy {
ResumeReviewProxy가 여러 UseCase를 모아서 호출하는 형태입니다. 
컨트롤러에서 각각의 UseCase를 직접 호출하지 않고 Proxy를 통해 호출하도록 중앙화된 구조를 제공하고싶었고 API호출을 위임한다의 의미로 proxy로 사용하기는했습니다 🙏🏻

2024-11-23 08:23 UTC, dbeod2 commented on src/main/java/com/api/resume/application/service/ResumeReviewQueryService.java
> +        return ResumeReviewDtoConverter.INSTANCE.toResumeReviewListDtos(resumeReviews);
네! converter 리뷰주신부분은 검토해보겠습니다.

2024-11-23 08:32 UTC, dbeod2 commented on src/main/java/com/api/resume/adapter/persistence/ResumeReviewSpecificationBuilder.java
> +        Specification<ResumeReview> spec = Specification.where(null);
아니요 querydsl로 작성해본적은 없습니다~

2024-11-26 01:27 UTC, dbeod2 commented
restdoc 캡쳐 화면입니다~ 
![프로젝트 회고 목록](https://github.com/user-attachments/assets/19646f63-f129-4c50-82cd-5ad89429a178)
![프로젝트 회고 상세](https://github.com/user-attachments/assets/54a59f71-a818-4080-bb3c-a52caa512ed5)
![프로젝트 회고 등록](https://github.com/user-attachments/assets/9b883f2c-e88a-4376-986c-8f01d7d766af)
![프로젝트 회고 수정](https://github.com/user-attachments/assets/d20c6a65-4963-4a85-9db8-fa77d5339c04)
![프로젝트 회고 삭제](https://github.com/user-attachments/assets/ff57bbe0-579b-40ae-b86e-d6573b3121b8)

2025-01-12 13:08 UTC, merged